apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-alb-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:

          # Root → Apache UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: apache
                port:
                  number: 8080

          # Catalog API
          - path: /catalog
            pathType: Prefix
            backend:
              service:
                name: catalog
                port:
                  number: 8080

          # Customer API
          - path: /customer
            pathType: Prefix
            backend:
              service:
                name: customer
                port:
                  number: 8080

          # Order API
          - path: /order
            pathType: Prefix
            backend:
              service:
                name: order
                port:
                  number: 8080
